- name: use image_address from local registry
  set_fact:
    image_address: "{{docker_insecure_registry_server_ip}}:{{docker_insecure_registry_server_port}}/{{ ceph_docker_image }}:{{ ceph_docker_image_tag }}"
  when: docker_use_local_registry

- name: use image_address from extenal registry
  set_fact:
    image_address: "{{ ceph_docker_image }}:{{ ceph_docker_image_tag }}"
  when: not docker_use_local_registry
  
- name: run docker with KV store
  docker_container:
    name: "{{ mgr_name }}"
    state: started
    image: "{{ image_address }}"
    volumes:
      - /var/lib/ceph/:/var/lib/ceph/
      - /etc/localtime:/etc/localtime
    env:
      CEPH_PUBLIC_NETWORK: "{{ ceph_public_network }}"
      KV_TYPE: "{{ kv_type }}"
      KV_IP: "{{ kv_endpoint }}"
      KV_PORT: "{{kv_port}}"
    network_mode: host
    command: mgr
    restart_policy: unless-stopped
