# #host_var
# ceph_conf_file:
#     path: /tmp/ceph.base
#     group: root
#     owner: root
#     mode: 0640
# ceph_parameters_file:
#     path: /tmp/ceph.parameters
#     group: root
#     owner: root
#     mode: 0640
# rules:
#   - name: hdd-replicate
#     class: hdd
#   - name: ssd-replicate
#     class: ssd
# pools:
#   - name: images
#     pg: 128
#     rule: hdd-replicate
#     application: rbd
#     size: 3
#     min_size: 2
#   - name: volumes
#     pg: 128
#     size: 3
#     min_size: 2
#     rule: hdd-replicate
#     application: rbd
    
# users:
#   - name: images
#     permission: "mon 'allow r' osd 'allow class-read object_prefix rbd_children, allow rwx pool=images, allow rwx pool=volumes'"
#   - name: volumes
#     permission: "mon 'allow r' osd 'allow class-read object_prefix rbd_children, allow rwx pool=images, allow rwx pool=volumes'"
#group_var
# dashboard_username: foo
# dashboard_password: bar
 