---
# #group-var
# ceph_public_network: 192.168.100.0/24
# docker_use_local_registry: false
# docker_insecure_registry_server_ip: 192.168.2.191
# ceph_docker_image: ceph/daemon
# ceph_docker_image_tag: tag-build-master-luminous-ubuntu-16.04
# host-var
# mon_name: ceph-mon
# mon_ip: 192.168.100.191
# role-var
# kv_type: etcd
# kv_endpoint: 192.168.100.195
# kv_port: 2379
# retries_mon: 5
# delay_retries_mon: 30
# #task-var make
# image_address: ceph/daemon


