---
- name: use image_address from local registry
  set_fact:
    image_address: "{{docker_insecure_registry_server_ip}}:{{docker_insecure_registry_server_port}}/{{ ceph_docker_image }}:{{ ceph_docker_image_tag }}"
  when: docker_use_local_registry

- name: use image_address from extenal registry
  set_fact:
    image_address: "{{ ceph_docker_image }}:{{ ceph_docker_image_tag }}"
  when: not docker_use_local_registry
- name: populate-kvstore
  include: populate-kvstore.yml

- name: run monitor with kv store
  docker_container:
    name: "{{ mon_name }}"
    state: started
    command: mon
    network_mode: host
    restart_policy: unless-stopped
    volumes: 
      - /var/lib/ceph:/var/lib/ceph
      - /etc/localtime:/etc/localtime
      - /var/run/ceph:/var/run/ceph 
    env:
      MON_IP: "{{ mon_ip }}"
      KV_TYPE: "{{ kv_type }}"
      KV_IP: "{{kv_endpoint}}"
      KV_PORT: "{{ kv_port }}"
      CEPH_PUBLIC_NETWORK: "{{ ceph_public_network }}"
    image: "{{image_address}}"
- name: put client host key
  command: "curl 'http://{{kv_endpoint}}:{{kv_port}}/v2/keys/ceph-config/ceph/client_host' -XPUT -d value=''"
  changed_when: false
  register: check_put
  failed_when: false
  until: check_put.rc == 0
  retries: 5
  delay: 2
  
- name: check mon up
  include: verify-mon.yml

  
#- name: update mon map
#  command: "docker exec {{mon_name}} ceph mon getmap -o /etc/ceph/monmap-ceph"
