---
# # group-var
# docker_use_local_registry: true
# docker_insecure_registry_server_ip: 192.168.1.192
# ceph_docker_image: ceph/daemon
# ceph_docker_image_tag: tag-build-master-luminous-ubuntu-16.04
# retries_osd: 5
# delay_retries_osd: 20
# host-var
# device_prepare:
#   - name: vdb
#     path: /dev/vdb
#   - name: vdc
#     path: /dev/vdc
#   - name: vdd
#     path: /dev/vdd
# osd_nodes:
#   - name: ceph-osd01
#     primary_disk: /dev/vdb
#   - name: ceph-osd02
#     primary_disk: /dev/vdc
#     wal_disk: /dev/vdd
#     db_disk: /dev/vdd
# role-var
# kv_type: etcd
# kv_endpoint: 192.168.100.195
# kv_port: 2379
# # task-var make
# image_address: "ceph/daemon"
