- name: Download etcd
  get_url: url="{{ etcd_download_url }}"
           dest=/tmp/etcd.tar.gz
- name: Unarchive etcd
  unarchive: copy=no
             src=/tmp/etcd.tar.gz
             dest=/tmp
             creates="/tmp/{{etcd_release}}/etcd"
- name: Copy binaries from archive into etcd dir
  synchronize: src="/tmp/{{etcd_release}}/{{ item }}"
               dest="{{ etcd_run_dir }}"
               archive=True
  delegate_to: "{{ inventory_hostname }}"
  with_items:
    - etcd
    - etcdctl
- name: Add etcd systemd service
  template: src=etcd/systemd/system/etcd.service.j2
            dest=/etc/systemd/system/etcd.service
            mode=0644
  when: ansible_service_mgr == "systemd"
  notify:
    - Reload systemd
    - Restart etcd
