#os
use_proxy: true
http_proxy: "http://192.168.5.8:3128"
https_proxy: "http://192.168.5.8:3128"
no_proxy: "localhost,127.0.0.1,storage01,storage02,storage03,storage04,.191,.192,.193,.194,10.10.100.191,192.168.2.191,192.168.100.191,192.168.200.191,192.168.100.192,192.168.100.193,192.168.100.194,192.168.100.195,192.168.2.192,192.168.2.193,192.168.2.194,192.168.2.195,192.168.200.192,192.168.200.193,192.168.200.194,192.168.200.195"

#etcd-keepalived
#etcd_interface is interface etcd connect each other
etcd_interface: ens5
etcd_run_dir: /usr/local/sbin
etcd_data_dir: /var/cache/etcd/state
etcd_user: root
keepalived_iface_vip: ens5
keepalived_role: SLAVE

#mon
mon_name: ceph-mon
mon_ip: 192.168.100.192

#mgr01
mgr_name: ceph-mgr
# osds
device_prepare:
  - name: vdd
    path: /dev/vdd
  - name: vde
    path: /dev/vde
  - name: vdf
    path: /dev/vdf
osd_nodes:
  - name: ceph-osd-vdd
    primary_disk: /dev/vdd
  - name: ceph-osd-vde
    primary_disk: /dev/vde
    wal_disk: /dev/vdf
    db_disk: /dev/vdf

