# ceph osd crush rule create-replicated rule-hdd default host hdd
# ceph osd crush rule create-replicated rule-ssd default host ssd
# ceph osd pool create images 128 rule-hdd
- name: create rules
  command: docker exec {{mon_name}} ceph osd crush rule create-replicated {{item.name}} default host {{item.class}}
  loop: "{{rules}}"
  ignore_errors: yes
- name: create pools
  command: docker exec {{mon_name}} ceph osd pool create {{item.name}} {{item.pg}} {{item.rule}}
  loop: "{{pools}}"
- name: conf pool size
  command: docker exec {{mon_name}} ceph osd pool set {{item.name}} size {{item.size}}
  when: item.size is defined
  loop: "{{pools}}"
- name: conf pool min size
  command: docker exec {{mon_name}} ceph osd pool set {{item.name}} min_size {{item.min_size}}
  when: item.min_size is defined
  loop: "{{pools}}"
- name: Enable application for pool
  command: docker exec {{mon_name}} ceph osd pool application enable {{ item.name }} {{ item.application }}
  when: item.application is defined
  loop: "{{ pools }}"
- name: create users
  command: docker exec {{mon_name}} ceph auth get-or-create client.{{ item.name }} 
  loop: "{{ users }}"
- name: set user permission
  command: "docker exec {{mon_name}} ceph auth caps client.{{item.name}} {{ item.permission }}"
  when: item.permission is defined
  loop: "{{ users }}"
